default/.dockerignore.j2
default/Dockerfile.j2
default/hokusai/build.yml.j2
default/hokusai/development.yml.j2
default/hokusai/test.yml.j2
nodejs/hokusai/build.yml.j2
nodejs/hokusai/development.yml.j2
nodejs/hokusai/test.yml.j2
rails-puma/Dockerfile.j2
rails-puma/hokusai/build.yml.j2
rails-puma/hokusai/development.yml.j2
rails-puma/hokusai/production.yml.j2
rails-puma/hokusai/staging.yml.j2
rails-puma/hokusai/test.yml.j2
rails-unicorn/hokusai/build.yml.j2
rails-unicorn/hokusai/development.yml.j2
rails-unicorn/hokusai/test.yml.j2

As discussed... details are in the individual commits.
Q: These templates do _not_ include the `hokusai/config.yml` configuration file, right? I was thinking it might be helpful to include a `pre-deploy: 'rake db:migrate'` in that file for Rails-style projects.
Will follow up with a few more questions.

Update templates based on most recent project experience

---

rails-puma/hokusai/staging.yml.j2

Makes `staging.yml` consistent with `production.yml`.

Update staging.yml to use HTTP to origin, like production.yml

---

default/hokusai/production.yml.j2
default/hokusai/staging.yml.j2
nodejs/hokusai/production.yml.j2
nodejs/hokusai/staging.yml.j2
rails-puma/hokusai/production.yml.j2
rails-puma/hokusai/staging.yml.j2

Follow-up to https://github.com/artsy/gravity/pull/12652 and https://github.com/artsy/volt/pull/4007 in which we settled on a best practice pattern for ensuring clean shutdown and connection draining for k8s pods

add shutdown sequence best practices

---

rails-puma/hokusai/production.yml.j2
rails-puma/hokusai/staging.yml.j2

Motivated by a discussion in a separate PR: https://github.com/artsy/pulse/pull/652
In the conversation there we think that PORT should be included in staging/production.yml. So I would like to add it to the template. Also want to add the following:
PUMA_WORKERS
PUMA_THREAD_MIN
PUMA_THREAD_MAX
MALLOC_ARENA_MAX
These PUMA vars are referred to in puma.config. They very likely should be tuned per application, so it seems reasonable to make it explicit. Although, I am not sure what default values are good, except for MALLOC_ARENA_MAX=2 which we are quite sure from experimentation.
Speaking of MALLOC_ARENA_MAX, which benefits sidekiq most. But we do not template sidekiq. Should we add?

Updated staging/production yml, to add PORT and some PUMA vars.

---

default/hokusai/production.yml.j2
default/hokusai/staging.yml.j2
nodejs/hokusai/production.yml.j2
nodejs/hokusai/staging.yml.j2
rails-puma/hokusai/production.yml.j2
rails-puma/hokusai/staging.yml.j2

This reverts commit e2ca76c299f437eace32d0c5271201d0a45223da.
Downgrade Deployment api versions from `apps/v1` to `extensions/v1beta1` as when applying via `kubectl` the API server downgrades the versions anyway and fails to populate deployment labels

Revert "upgrade deployments to apps/v1"

---

default/hokusai/production.yml.j2
default/hokusai/staging.yml.j2
nodejs/hokusai/production.yml.j2
nodejs/hokusai/staging.yml.j2
rails-puma/hokusai/production.yml.j2
rails-puma/hokusai/staging.yml.j2

- Reduce staging cpu request to 100m.
- Reduce prod cpu request to 200m.
- Nodejs, add NODE_OPTIONS env var which specifies max_old_space_size to equal memory request. (as is the case for metaphysics)

Changes to cpu request. Add Node env var for max old heap size.

---

README.md
default/.circleci/config.yml.j2
nodejs/.circleci/config.yml.j2
rails-puma/.circleci/config.yml.j2

Along with updating the [deployment playbook](https://github.com/artsy/README/blob/master/playbooks/deployments.md#tools), we should ensure that projects have the appropriate safeguards in place from the start. This PR adds the `block` step from [Horizon's orb](https://github.com/artsy/orbs/blob/master/src/release/release.yml) to all templates' release workflow.
A new `horizon_project_id` var can be provided during set-up time, but if it's not then `REPLACE_ME` is substituted in the `.circleci/config.yml`. (The README says that "Users will get a warning if trying to render a template with a defined but unspecified variable" but it looks more like an error in my local experiments.)

Check for deploy blocks prior to releasing

---

default/hokusai/production.yml.j2
default/hokusai/staging.yml.j2
nodejs/hokusai/production.yml.j2
nodejs/hokusai/staging.yml.j2
rails-puma/hokusai/production.yml.j2
rails-puma/hokusai/staging.yml.j2

The config block `{{ cloudflareIpSourceRanges|join(',') }}` should be rendered as a string into staging / production Yaml templates so wrap it with a `raw` tag.  @alexpopa-artsy and I ran into a `UndefinedError: 'cloudflareIpSourceRanges' is undefined` error when running `hokusai setup`
We may want to change the extensions of these templates to `.yml.j2.j2` so we end up with `.yml.j2` files in the repo.  Will follow up with another PR about this.

fix: wrap cloudflareIPSourceRanges in raw tag

---

default/hokusai/production.yml.j2
default/hokusai/staging.yml.j2
nodejs/hokusai/production.yml.j2
nodejs/hokusai/staging.yml.j2
rails-puma/hokusai/production.yml.j2
rails-puma/hokusai/staging.yml.j2

https://artsy.slack.com/archives/CA8SANW3W/p1610644120020700
Added `externalIngressAllowSourceIP` var to `s3://artsy-citadel/k8s/hokusai-vars.yml`. The var contains Cloudflare and internal IP ranges.
Update template so that we use this var for external ingress `whitelist-source-range` annotation.
Left  `{% endraw %}` in place but note that it didn't work for `hokusai-sandbox`.

feat: use externalIngressAllowSourceIP var for external ingress allow ip.

---

default/hokusai/production.yml.j2
default/hokusai/staging.yml.j2
nodejs/hokusai/production.yml.j2
nodejs/hokusai/staging.yml.j2
rails-puma/hokusai/production.yml.j2
rails-puma/hokusai/staging.yml.j2

In preparation for https://artsyproduct.atlassian.net/browse/PLATFORM-3175.
- Add cronjob to k8s spec template. Not every project has a cronjob, but many do, and there's a bunch of settings we'd like to lock down (`safe-to-evict`, `concurrencyPolicy`, `backoffLimit`, `nodeAffinity`).
- Remove `preStop` sleep. It was to ensure that the app container terminates after Nginx sidecar. Now that there's no sidecar, I don't see a reason for it.

feat: add cronjob to templates, and misc.

---

default/hokusai/production.yml.j2
default/hokusai/staging.yml.j2
nodejs/hokusai/production.yml.j2
nodejs/hokusai/staging.yml.j2
rails-puma/hokusai/production.yml.j2
rails-puma/hokusai/staging.yml.j2

Since in container spec we already give a name to its port, it seems good to have the service point to that name.

feat: use name for service target port

---

default/hokusai/production.yml.j2
default/hokusai/staging.yml.j2
nodejs/hokusai/production.yml.j2
nodejs/hokusai/staging.yml.j2
rails-puma/hokusai/production.yml.j2
rails-puma/hokusai/staging.yml.j2

In https://github.com/artsy/artsy-hokusai-templates/pull/30, I thought that `preStop` hook of the app container is no longer required.
However, per discussion in https://github.com/artsy/gravity/pull/13917, the hook should still be required. Therefore, adding it back.

fix: put preStop hook back.

---

rails-puma/config/puma.config

Follow up on https://github.com/artsy/impulse/pull/740
Currently the [puma thread count default](https://github.com/artsy/artsy-hokusai-templates/blob/c4d9c82dccfdfd07e3b4d4f80ec0c514f2402355/rails-puma/config/puma.config#L8) (0 to 16) doesn't match the [default db pool size](https://github.com/rails/rails/blob/3dd0af563b5ebdccf1e3c1993f8a64f4ab5fce48/railties/lib/rails/generators/rails/app/templates/config/databases/postgresql.yml.tt#L22) (5) of rails. This requires manual changes when setting up a new app; otherwise the app might suffer from insufficient db connection during high traffic.
This updates the default and uses the same `RAILS_MAX_THREADS` environment variable. Individual app can still tweak it if necessary.

feat: match puma thread count default with rails db pool size

---

rails-puma/hokusai/production.yml.j2
rails-puma/hokusai/staging.yml.j2

as part of cron-project task, i've been trying to true up projects' ymls to template. for sidekiq, it's been difficult not being able to refer to a template for it. suggesting to add.

feat: add sidekiq to rails template.

---

default/.circleci/config.yml.j2
nodejs/.circleci/config.yml.j2
rails-puma/.circleci/config.yml.j2

I set up a new project with our templates (https://github.com/artsy/power/pull/67), and discovered that [the build](https://app.circleci.com/pipelines/github/artsy/power/12/workflows/16f6f37e-7b26-4620-8bdc-d3ce22060b29) didn't do what I expected because the `.circleci/config.yml` template assumes the `master` branch name. (Later fixed in https://github.com/artsy/power/pull/69.)
This PR updates our templates to use `main` instead. Since they're almost always used by new repositories (which will default to `main`), I don't think we need to add any special handling for the `master` alternative.

Update templates to prefer main over master branch name

---

default/hokusai/production.yml.j2
default/hokusai/staging.yml.j2
nodejs/hokusai/production.yml.j2
nodejs/hokusai/staging.yml.j2
rails-puma/hokusai/production.yml.j2
rails-puma/hokusai/staging.yml.j2

https://artsyproduct.atlassian.net/browse/PLATFORM-3612
Encountered this restriction when re-configuring Acceleration's specs.
Make a comment about it in the templates so in the future it's apparent to folks setting up new projects.

feat: mention k8s 15 char limit on a port name.

---

default/.circleci/config.yml.j2
nodejs/.circleci/config.yml.j2
nodejs/hokusai/production.yml.j2
nodejs/hokusai/staging.yml.j2
rails-puma/.circleci/config.yml.j2
rails-puma/hokusai/production.yml.j2
rails-puma/hokusai/staging.yml.j2

Use latest versions of Artsy managed orbs
---
https://artsy.slack.com/archives/CA8SANW3W/p1649961862718249
We decided there's no need for projects to pin version of Artsy-managed CircleCI orbs.
Pinning the version requires us to update every project (through Renovate or manually) when there's a new orb release, which does not provide any additional safety, because we do not test on an official release, nor do we roll-out in batches of projects.
We test on a [canary (beta) testing](https://artsy.slack.com/archives/CA8SANW3W/p1649961862718249) version (prior to the release), which seems sufficiently safe.
Please note this is only about Artsy-managed orbs. Non-Artsy orbs (which the templates do not cover) should probably continue to be pin'd.
track app version
---
Follows: …

feat: use latest version of artsy managed orbs, and track app version in k8s label

---

nodejs/Dockerfile.j2
rails-puma/Dockerfile.j2

https://github.com/artsy/gravity/pull/16843#discussion_r1332163206
- `--no-cache` and `--quiet` are options of `apk add` command (not `apk` itself), so it should be `apk add --no-cache --quiet`.
- there's no `--update` option for `apk` or `apk add`
```
/ # cat /etc/issue
Welcome to Alpine Linux 3.18
Kernel \r on an \m (\l)
/ # apk --help | grep update
update     Update repository indexes
/ # apk add --help | grep update
-U, --update-cache    Alias for '--cache-max-age 1'
```

fix: apk command

---

default/hokusai/production.yml.j2
default/hokusai/staging.yml.j2
nodejs/hokusai/production.yml.j2
nodejs/hokusai/staging.yml.j2
rails-puma/hokusai/production.yml.j2
rails-puma/hokusai/staging.yml.j2

Similar to https://github.com/artsy/opstools/pull/58 and its many follow-ups. This project's specs are in subdirectories so didn't match the general script. Though, now that I think about it, the script can probably be improved to match `**/hokusai/*.yml*` instead...

chore: address kubernetes spec deprecations

---

rails-puma/hokusai/staging.yml.j2

Self-assigning this deprecation fix leftover from https://github.com/artsy/artsy-hokusai-templates/pull/42.

fix: one more deprecation for kubernetes spec

---

rails-puma/hokusai/production.yml.j2
rails-puma/hokusai/staging.yml.j2

Resolves https://artsyproduct.atlassian.net/browse/PHIRE-338
Updating template after [Gravity](https://github.com/artsy/gravity/pull/16956) and other projects.

fix: exec probes without timeout setting
